### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by millpoint** [rtklibexplorer/rtklib-py#1]
F:\RTKLIB\rtklib-python-ppk\src>run_ppk.py        "
Traceback (most recent call last):
  File "F:\RTKLIB\rtklib-python-ppk\src\run_ppk.py", line 35, in <module>
    import __ppk_config as cfg
  File "F:\RTKLIB\rtklib-python-ppk\src\__ppk_config.py", line 3, in <module>
    from rtkcmn import uGNSS, rSIG
  File "F:\RTKLIB\rtklib-python-ppk\src\rtkcmn.py", line 11, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by rtklibexplorer** [comment]
Rtklib-py uses the Numpy library so it must be installed before running.  Search for "install numpy" on Google to find more info.
